#Giving oauth_2 error

version: 2 # use CircleCI 2.0
jobs: # A basic unit of work in a run
  build: 
    working_directory: ~/timelapsed
    docker:
      - image: circleci/python:3.6.4
    steps: # steps that comprise the `build` job
      - checkout
      - run:
          command: |
            echo 'export DJANGO_SETTINGS_MODULE= $DJANGO_SETTINGS_MODULE' >> $BASH_ENV
            echo 'export SECRET_KEY= $SECRET_KEY' >> $BASH_ENV
            sudo pip install --upgrade pip setuptools wheel
            sudo pip install pipenv
            sudo pipenv install
            cd backend
            sudo pipenv run python manage.py test