version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            cd backend
            pipenv run "python manage.py test"