# version: 2
# jobs:
#   build:
#     machine: true
#     steps:
#       - run:
#           command: |
#             sudo pip install pipenv
#             pipenv install
#             pipenv shell
#             cd backend
#             pipenv run "python manage.py test"

version: 2 # use CircleCI 2.0
jobs: # A basic unit of work in a run
  build: 
    working_directory: ~/timelapsed
    machine: true
    steps: # steps that comprise the `build` job
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            cd ..
            ls
            cd backend
            pipenv run python manage.py test
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1